---
- name: (completion) create completion dir
  ansible.builtin.file:
    path: "{{ takel_packer_completion_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: (completion) copy completion file
  ansible.builtin.copy:
    src: packer
    dest: "{{ takel_packer_bash_completion }}"
    owner: root
    group: root
    mode: '0644'
