---
- name: (main) include install
  import_tasks: install.yml
  tags:
    - takel
    - takel_packer
    - takel_packer_install

- name: (main) include completion
  import_tasks: completion.yml
  tags:
    - takel
    - takel_packer
    - takel_packer_completion
